import { useMemo, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { ArrowDown, ArrowUpRight, Check, ChevronRight, MapPin, MessageCircle, Minus, Plus } from "lucide-react";
import { buttonVariants } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { getDestination } from "@/data/destinations";
import { openWhatsApp } from "@/lib/whatsapp";
import { cn } from "@/lib/utils";
import { Breadcrumbs, EnquiryForm, SectionHeading, Seo, SiteLayout } from "@/components/site/Shared";
import type { Destination, Itinerary } from "@/data/types";

export default function DestinationDetail() {
  const { slug } = useParams();
  const destination = getDestination(slug) ?? getDestination("bali")!;
  return <DestinationDetailContent key={destination.slug} destination={destination} />;
}

function DestinationDetailContent({ destination }: { destination: Destination }) {
  const [activeItinerary, setActiveItinerary] = useState(destination.itineraries[0]?.id);
  const [openDays, setOpenDays] = useState<string[]>([destination.itineraries[0]?.days[0]?.day ?? "01"]);
  const activeJourney = destination.itineraries.find((item) => item.id === activeItinerary) ?? destination.itineraries[0];
  const breadcrumbItems = useMemo(() => [{ label: "Destinations", href: "/destinations" }, { label: destination.name }], [destination.name]);
  return <SiteLayout><Seo title={`${destination.name} journeys`} description={destination.heroDescription} />
    <section className="relative min-h-[100svh] overflow-hidden bg-[#0d7a84] px-5 pb-12 pt-28 text-white sm:min-h-[720px] sm:px-8 sm:pb-20 sm:pt-40 lg:min-h-[780px] lg:px-12 lg:pb-24 lg:pt-48" data-testid="destination-hero"><img src={destination.image} alt={`${destination.name} landscape`} className="animate-cinematic-reveal absolute inset-0 h-full w-full scale-[1.03] object-cover opacity-80 saturate-[0.92] contrast-[1.05]" /><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(6,39,43,0.94),rgba(6,39,43,0.48)_52%,rgba(6,39,43,0.08)),linear-gradient(0deg,rgba(6,39,43,0.34),transparent_58%)]" /><div className="relative mx-auto max-w-[1440px]"><Breadcrumbs items={breadcrumbItems} /><div className="mt-14 max-w-4xl sm:mt-24"><p className="font-mono text-[9px] uppercase tracking-[0.24em] text-[#a8f1ef] sm:text-[10px] sm:tracking-[0.28em]">{destination.country} · {destination.region}</p><h1 className="mt-4 text-balance font-serif text-[3.45rem] font-normal leading-[0.9] tracking-[-0.045em] sm:mt-5 sm:text-9xl lg:text-[10rem]">{destination.name}</h1><p className="mt-5 max-w-xl text-[15px] leading-[1.7] text-white/75 sm:mt-7 sm:text-lg sm:leading-[1.75]">{destination.heroDescription}</p><div className="mt-7 grid grid-cols-2 gap-x-4 gap-y-4 border-t border-white/25 pt-5 text-xs text-white/65 sm:mt-9 sm:flex sm:flex-wrap sm:gap-x-9 sm:gap-y-4 sm:pt-6 sm:text-sm"><span><strong className="block font-serif text-xl font-normal text-white sm:text-2xl">{destination.duration}</strong>Typical journey</span><span><strong className="block font-serif text-xl font-normal text-white sm:text-2xl">{destination.bestTime}</strong>Best time to visit</span><span className="col-span-2"><strong className="block font-serif text-xl font-normal text-white sm:text-2xl">{destination.popularWith}</strong>Popular with</span></div><div className="mt-7 grid grid-cols-1 gap-3 sm:mt-9 sm:flex sm:flex-row"><a href="#request" className={cn(buttonVariants({ variant: "secondary", size: "lg" }), "min-h-12 justify-center gap-2 rounded-none bg-white text-[#0d7a84] hover:bg-[#e5f7f5]")} data-testid="destination-request-button">Request this trip <ArrowDown className="h-4 w-4" /></a><button type="button" onClick={() => openWhatsApp(`Hi Tentwood Trips! I’m interested in a ${destination.name} journey.`)} className="inline-flex min-h-12 items-center justify-center gap-2 border border-white/40 px-5 text-sm font-medium text-white transition-colors hover:bg-white/10" data-testid="destination-whatsapp-button">WhatsApp Tentwood <MessageCircle className="h-4 w-4" /></button></div></div></div></section>
    <section className="mx-auto max-w-[1440px] px-5 py-16 sm:px-8 sm:py-20 lg:px-12 lg:py-32"><div className="grid gap-10 sm:gap-16 lg:grid-cols-[0.82fr_1.18fr] lg:items-center"><div><SectionHeading eyebrow="A closer look" title={`About ${destination.name}`} copy={destination.about} /><div className="mt-6 flex flex-wrap gap-2 sm:mt-8">{destination.tags.map((tag) => <Badge key={tag} variant="outline" className="rounded-none border-[#0d7a84]/25 px-3 py-1 font-mono text-[9px] uppercase tracking-[0.16em] text-[#0d7a84]">{tag}</Badge>)}</div></div><div className="grid grid-cols-2 gap-3 sm:gap-4"><img src={destination.secondaryImage} alt={`${destination.name} architecture or landscape`} className="aspect-[4/5] w-full object-cover" loading="lazy" /><img src={destination.image} alt={`${destination.name} travel moment`} className="mt-8 aspect-[4/5] w-full object-cover sm:mt-14" loading="lazy" /></div></div></section>
    <section className="bg-[#f2ede4] px-5 py-16 sm:px-8 sm:py-20 lg:px-12 lg:py-32"><div className="mx-auto max-w-[1440px]"><SectionHeading eyebrow="The reasons to go" title={`Why ${destination.name}?`} copy="The places that stay with you are usually the ones that offer more than one kind of beauty." /><div className="mt-10 grid gap-7 sm:mt-14 sm:grid-cols-2 lg:grid-cols-4">{(destination.reasons.length ? destination.reasons : [{ title: "A different pace", copy: "A considered route built around the details that make a place feel alive." }, { title: "The local table", copy: "Good food, found in the right rooms and made by the right hands." }, { title: "Room to wander", copy: "Enough structure to feel held, enough freedom to make it yours." }, { title: "Human guidance", copy: "An expert who knows when to recommend and when to leave you alone." }]).map((reason, index) => <div key={reason.title} className="border-t border-[#1a1d20]/15 pt-5"><span className="font-serif text-3xl italic text-[#0d7a84]/50">0{index + 1}</span><h3 className="mt-5 font-serif text-[1.75rem] font-normal sm:mt-8 sm:text-3xl">{reason.title}</h3><p className="mt-3 text-sm leading-[1.75] text-[#5a6065]">{reason.copy}</p></div>)}</div></div></section>
    {destination.experiences.length > 0 && <section className="mx-auto max-w-[1440px] px-5 py-16 sm:px-8 sm:py-20 lg:px-12 lg:py-32"><SectionHeading eyebrow="Do it differently" title="Experiences worth making time for" copy="Not a checklist. Just a few possibilities to make the journey yours." /><div className="-mx-5 mt-9 flex snap-x snap-mandatory gap-4 overflow-x-auto px-5 pb-3 scroll-px-5 [scrollbar-width:none] sm:mx-0 sm:mt-12 sm:grid sm:grid-cols-2 sm:gap-6 sm:px-0 lg:grid-cols-4 [&::-webkit-scrollbar]:hidden">{destination.experiences.map((experience) => <article key={experience.title} className="group min-w-[82vw] max-w-[330px] snap-start sm:min-w-0 sm:max-w-none" data-testid={`experience-card-${experience.title.toLowerCase().replaceAll(" ", "-")}`}><div className="overflow-hidden"><img src={experience.image} alt={experience.title} loading="lazy" className="aspect-[4/5] w-full object-cover transition duration-700 group-hover:scale-105" /></div><div className="mt-4 flex items-start justify-between gap-4 sm:mt-5"><div><h3 className="font-serif text-2xl font-normal">{experience.title}</h3><p className="mt-2 text-sm leading-[1.75] text-[#5a6065]">{experience.description}</p></div>{experience.duration && <span className="shrink-0 pt-1 font-mono text-[9px] uppercase tracking-[0.14em] text-[#0d7a84]">{experience.duration}</span>}</div></article>)}</div></section>}
    {destination.itineraries.length > 0 && activeJourney && <ItineraryEditorial destination={destination} activeJourney={activeJourney} activeItinerary={activeItinerary} openDays={openDays} onSelect={(itinerary) => { setActiveItinerary(itinerary.id); setOpenDays(itinerary.days[0] ? [itinerary.days[0].day] : []); }} onToggleDay={(day) => setOpenDays((current) => current.includes(day) ? current.filter((item) => item !== day) : [...current, day])} />}
    <section className="mx-auto max-w-[1440px] px-5 py-16 sm:px-8 lg:px-12 lg:py-24"><div className="-mx-5 flex snap-x snap-mandatory gap-4 overflow-x-auto px-5 pb-2 scroll-px-5 md:mx-0 md:grid md:grid-cols-2 md:gap-6 md:overflow-visible md:px-0"><div className="min-w-[88vw] snap-start border border-[#0d7a84]/15 bg-[#e9f3f1] p-5 sm:p-8 md:min-w-0"><h3 className="font-mono text-[10px] uppercase tracking-[0.2em] text-[#0d7a84]">Inclusions</h3><ul className="mt-5 space-y-3 text-sm text-[#1a1d20]">{(activeJourney?.inclusions ?? ["Handpicked accommodation", "Selected experiences", "Local assistance", "Daily breakfast"]).map((item) => <li key={item} className="flex gap-3"><Check className="h-4 w-4 shrink-0 text-[#0d7a84]" />{item}</li>)}</ul></div><div className="min-w-[88vw] snap-start border border-[#1a1d20]/10 bg-[#f8f5ee] p-5 sm:p-8 md:min-w-0"><h3 className="font-mono text-[10px] uppercase tracking-[0.2em] text-[#5a6065]">Exclusions</h3><ul className="mt-5 space-y-3 text-sm text-[#5a6065]">{(activeJourney?.exclusions ?? ["International flights", "Personal expenses", "Meals not mentioned", "Travel insurance unless specified"]).map((item) => <li key={item} className="flex gap-3"><span className="text-[#d98a6c]">×</span>{item}</li>)}</ul></div></div></section>
    <section className="bg-[#f2ede4] px-5 py-16 sm:px-8 lg:px-12 lg:py-24"><div className="mx-auto max-w-[1440px]"><div className="grid gap-8 lg:grid-cols-[0.7fr_1.3fr] lg:items-end"><SectionHeading eyebrow="From people who went" title="The details make the memory." /><div className="grid gap-4 sm:grid-cols-2">{destination.reviews.map((review) => <blockquote key={review.name} className="border-l-2 border-[#0d7a84] pl-5"><p className="font-serif text-xl leading-snug">“{review.quote}”</p><footer className="mt-4 text-xs text-[#5a6065]">{review.name} <span className="mx-1">·</span> {review.trip}</footer></blockquote>)}</div></div></div></section>
    <section id="request" className="mx-auto max-w-[1440px] scroll-mt-20 px-5 py-16 sm:px-8 lg:px-12 lg:py-24"><div className="grid gap-8 sm:gap-10 lg:grid-cols-[0.7fr_1.3fr] lg:items-start"><div className="lg:sticky lg:top-28"><SectionHeading eyebrow="Make it yours" title="Ready when you are." copy="Start with one detail or bring us the whole dream. There’s no wrong way to begin." /><div className="mt-6 flex items-center gap-3 border-t border-[#1a1d20]/10 pt-5 sm:mt-8"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-[#e9f3f1] text-[#0d7a84]"><MapPin className="h-4 w-4" /></span><div><p className="text-sm font-medium">{destination.name}, your way</p><p className="text-xs text-[#5a6065]">From {destination.priceFrom} per person</p></div></div></div><EnquiryForm key={activeJourney?.id} destination={destination} itinerary={activeJourney?.name} /></div></section>
    <section className="bg-[#0d7a84] px-5 py-14 text-center text-white sm:px-8 lg:px-12" data-testid="destination-final-cta"><p className="font-mono text-[9px] uppercase tracking-[0.2em] text-[#a8f1ef] sm:text-[10px]">Still deciding?</p><h2 className="mt-3 font-serif text-[2.15rem] leading-tight sm:text-4xl">Talk to a Tentwood travel expert.</h2><button type="button" onClick={() => openWhatsApp(`Hi Tentwood Trips! I’m still deciding about ${destination.name}.`)} className="mt-7 inline-flex min-h-12 w-full items-center justify-center gap-2 border border-white/40 px-5 text-sm transition-colors hover:bg-white/10 sm:w-auto" data-testid="destination-final-whatsapp-button">WhatsApp Tentwood <MessageCircle className="h-4 w-4" /></button></section>
  </SiteLayout>;
}

function ItineraryEditorial({ destination, activeJourney, activeItinerary, openDays, onSelect, onToggleDay }: { destination: Destination; activeJourney: Itinerary; activeItinerary?: string; openDays: string[]; onSelect: (itinerary: Itinerary) => void; onToggleDay: (day: string) => void }) {
  return <section className="bg-[#17383c] px-5 py-16 text-white sm:px-8 sm:py-20 lg:px-12 lg:py-32" data-testid="itineraries-section">
    <div className="mx-auto max-w-[1440px]"><SectionHeading eyebrow="The main event" title="Choose your journey" copy={`A day-by-day way into ${destination.name}, designed to be made personal with our travel team.`} light />
      <div className="mt-10 grid gap-8 sm:mt-14 sm:gap-10 lg:grid-cols-[0.72fr_1.28fr]">
        <aside className="lg:sticky lg:top-28 lg:self-start">
          <div className="relative min-h-[290px] overflow-hidden border border-white/12 sm:min-h-[320px]">
            <img src={activeJourney.image} alt={activeJourney.name} loading="lazy" className="absolute inset-0 h-full w-full object-cover opacity-70" />
            <div className="absolute inset-0 bg-gradient-to-t from-[#102f33] via-[#102f33]/25 to-transparent" />
            <div className="relative flex min-h-[290px] flex-col justify-end p-5 sm:min-h-[320px] sm:p-6"><p className="font-mono text-[9px] uppercase tracking-[0.22em] text-[#a8f1ef]">{activeJourney.route}</p><h3 className="mt-3 font-serif text-[2rem] font-normal leading-tight sm:text-4xl">{activeJourney.name}</h3><p className="mt-3 max-w-sm text-sm leading-[1.7] text-white/65">{activeJourney.summary}</p><div className="mt-5 flex items-end justify-between gap-3 border-t border-white/18 pt-4 sm:mt-6 sm:pt-5"><span className="text-xs text-white/55">{activeJourney.duration}</span><span className="font-serif text-xl sm:text-2xl">{activeJourney.price}</span></div></div>
          </div>
          {destination.itineraries.length > 1 && <div className="-mx-5 mt-3 flex snap-x snap-mandatory gap-2 overflow-x-auto px-5 pb-2 scroll-px-5 lg:mx-0 lg:flex-col lg:px-0" data-testid="itinerary-options">{destination.itineraries.map((itinerary, index) => <button key={itinerary.id} type="button" onClick={() => onSelect(itinerary)} className={cn("flex min-h-16 min-w-[82vw] snap-start cursor-pointer items-center gap-3 border px-4 py-3 text-left transition-colors sm:min-w-[260px] sm:gap-4 sm:py-4 lg:min-w-0", activeItinerary === itinerary.id ? "border-[#a8f1ef]/60 bg-white/10" : "border-white/12 hover:bg-white/5")} data-testid={`itinerary-select-${itinerary.id}`}><span className="font-serif text-2xl italic text-[#a8f1ef]/60">0{index + 1}</span><span className="min-w-0 flex-1"><span className="block truncate font-serif text-lg sm:text-xl">{itinerary.name}</span><span className="mt-1 block text-[11px] text-white/50 sm:text-xs">{itinerary.duration} · from {itinerary.price}</span></span><ChevronRight className="h-4 w-4 shrink-0 text-[#a8f1ef]" /></button>)}</div>}
          <Link to="#request" className="mt-5 inline-flex min-h-11 items-center gap-2 border-b border-[#a8f1ef]/50 pb-1 text-sm text-[#a8f1ef] sm:mt-6 sm:pb-2" data-testid={`itinerary-request-${activeJourney.id}`}>Plan this journey <ArrowUpRight className="h-4 w-4" /></Link>
        </aside>
        <div className="border-t border-white/16" data-testid="itinerary-timeline"><div className="flex items-center justify-between gap-3 py-5"><p className="font-mono text-[9px] uppercase tracking-[0.22em] text-[#a8f1ef]">The journey, day by day</p><p className="hidden text-xs text-white/45 min-[390px]:block">Tap a day for the story</p></div>
          {activeJourney.days.map((day, index) => { const open = openDays.includes(day.day); return <article key={day.day} className="relative border-t border-white/14" data-testid={`itinerary-day-${day.day}`}>
            <button type="button" onClick={() => onToggleDay(day.day)} className="group grid min-h-[76px] w-full cursor-pointer grid-cols-[44px_1fr_44px] items-center gap-3 py-4 text-left sm:min-h-0 sm:grid-cols-[92px_1fr_auto] sm:gap-4 sm:py-8" data-testid={`itinerary-day-toggle-${day.day}`} aria-expanded={open}>
              <span className="font-serif text-3xl italic text-[#a8f1ef]/55 sm:text-5xl">{day.day}</span><span className="min-w-0"><span className="block font-mono text-[8px] uppercase tracking-[0.2em] text-white/40">Day {String(index + 1).padStart(2, "0")}</span><span className="mt-1 block text-balance font-serif text-xl font-normal leading-tight sm:text-3xl">{day.title}</span></span><span className="grid h-11 w-11 place-items-center rounded-full border border-white/20 text-[#a8f1ef] transition-colors group-hover:bg-white/8 sm:h-9 sm:w-9">{open ? <Minus className="h-4 w-4" /> : <Plus className="h-4 w-4" />}</span>
            </button>
            {open && <div className="animate-itinerary-reveal grid gap-4 pb-6 pl-[56px] sm:grid-cols-[1fr_auto] sm:gap-5 sm:pb-8 sm:pl-[108px]"><p className="max-w-xl text-sm leading-[1.8] text-white/62 sm:leading-[1.85]">{day.details}</p><div className="flex flex-wrap gap-2 sm:justify-end">{day.tags.map((tag) => <span key={tag} className="h-fit border border-[#a8f1ef]/25 px-2 py-1 font-mono text-[8px] uppercase tracking-[0.15em] text-[#a8f1ef]">{tag}</span>)}</div></div>}
          </article>; })}
        </div>
      </div>
    </div>
  </section>;
}