import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { ArrowRight, ArrowUpRight, ChevronLeft, ChevronRight, Heart, MessageCircle, Play, Sparkles } from "lucide-react";
import { buttonVariants } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { destinations, domesticDestinations, visaFreeDestinations } from "@/data/destinations";
import { journeys } from "@/data/journeys";
import { featuredCampaign } from "@/data/campaigns";
import { travellerReviews } from "@/data/reviews";
import { openWhatsApp } from "@/lib/whatsapp";
import { cn } from "@/lib/utils";
import { DestinationCard, FilterBar, JourneyCard, SearchBar, SectionHeading, Seo, SiteLayout } from "@/components/site/Shared";

export default function Home() {
  const [filters, setFilters] = useState<Record<string, string>>({ Destination: "All Destinations", Budget: "All budgets", "Travel type": "All travellers", Duration: "Any duration" });
  const [reviewIndex, setReviewIndex] = useState(0);
  const visibleJourneys = useMemo(() => journeys.filter((journey) => (filters.Destination === "All Destinations" || journey.destination === filters.Destination) && (filters.Budget === "All budgets" || journey.budget === filters.Budget) && (filters["Travel type"] === "All travellers" || journey.travelType === filters["Travel type"])), [filters]);
  useEffect(() => { const reduce = window.matchMedia("(prefers-reduced-motion: reduce)").matches; if (reduce) return; const timer = window.setInterval(() => setReviewIndex((index) => (index + 1) % travellerReviews.length), 3000); return () => window.clearInterval(timer); }, []);
  const review = travellerReviews[reviewIndex];
  return <SiteLayout><Seo title="Travel, thoughtfully designed" description="Tentwood Trips creates curated journeys, beautiful places and experiences designed around the way you travel." />
    <section className="relative min-h-[720px] overflow-hidden bg-[#0d7a84] px-5 pb-16 pt-32 text-white sm:px-8 lg:min-h-[790px] lg:px-12 lg:pt-44" data-testid="home-hero">
      <img src="https://images.unsplash.com/photo-1540202404-a2f29016b523?auto=format&fit=crop&w=2200&q=88" alt="Aerial view of a tropical island and turquoise sea" className="absolute inset-0 h-full w-full object-cover opacity-70" />
      <div className="absolute inset-0 bg-gradient-to-r from-[#0d353b]/85 via-[#0d353b]/35 to-transparent" />
      <div className="absolute bottom-0 left-0 right-0 h-40 bg-gradient-to-t from-[#fdfbf7] to-transparent" />
      <div className="relative mx-auto flex min-h-[570px] max-w-[1440px] flex-col justify-between">
        <div className="max-w-3xl"><div className="flex items-center gap-3"><span className="h-px w-9 bg-[#9de9e6]" /><span className="font-mono text-[10px] uppercase tracking-[0.24em] text-[#b6eeec]">Curated journeys · Since 2018</span></div><h1 className="mt-6 max-w-3xl font-serif text-5xl leading-[1.02] tracking-tight sm:text-7xl lg:text-[6.7rem]">Travel,<br /><em className="font-normal text-[#a8f1ef]">thoughtfully</em> designed.</h1><p className="mt-6 max-w-lg text-base leading-relaxed text-white/78 sm:text-lg">Curated journeys, beautiful places and experiences designed around the way you travel.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link to="/destinations" className={cn(buttonVariants({ variant: "secondary", size: "lg" }), "justify-center gap-2 bg-white text-[#0d7a84] hover:bg-[#e5f7f5]")} data-testid="hero-explore-button">Explore destinations <ArrowUpRight className="h-4 w-4" /></Link><button type="button" onClick={() => openWhatsApp("Hi Tentwood Trips! I’d like to plan a thoughtful journey.")} className="inline-flex h-11 items-center justify-center gap-2 border border-white/45 px-5 text-sm font-medium text-white transition-colors hover:bg-white/10" data-testid="hero-plan-trip-button">Plan my trip <MessageCircle className="h-4 w-4" /></button></div></div>
        <div className="mt-16 w-full max-w-2xl border border-white/30 bg-white/90 p-5 text-[#1a1d20] shadow-2xl backdrop-blur-sm sm:p-7" data-testid="hero-search-panel"><div className="mb-4 flex items-center justify-between"><span className="font-mono text-[10px] uppercase tracking-[0.2em] text-[#0d7a84]">Begin anywhere</span><span className="flex items-center gap-1.5 text-xs text-[#5a6065]"><Sparkles className="h-3.5 w-3.5 text-[#d98a6c]" /> Personalised by people</span></div><SearchBar /></div>
      </div>
    </section>
    <section className="mx-auto max-w-[1440px] px-5 py-16 sm:px-8 lg:px-12 lg:py-24" data-testid="popular-journeys-section"><SectionHeading eyebrow="A good place to begin" title="Journeys travellers are choosing" copy="Discover where Tentwood travellers are heading next. Every route starts with a conversation, not a checkout." /><div className="mt-9"><FilterBar activeFilters={filters} setActiveFilters={setFilters} /><div className="mt-7 flex gap-5 overflow-x-auto pb-4 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden" data-testid="journey-carousel">{(visibleJourneys.length ? visibleJourneys : journeys).map((journey) => <JourneyCard key={journey.id} journey={journey} />)}</div></div></section>
    <section className="bg-[#e9f3f1] px-5 py-16 sm:px-8 lg:px-12 lg:py-24" data-testid="why-tentwood-section"><div className="mx-auto max-w-[1440px]"><SectionHeading eyebrow="The Tentwood way" title="Why travel with Tentwood?" copy="The best journeys leave room for the unexpected. We take care of the considered details, so you can be fully there." /><div className="mt-12 grid gap-8 md:grid-cols-2 lg:grid-cols-4">{[{ number: "01", title: "Thoughtfully curated", copy: "Every journey is built around places and experiences worth remembering." }, { number: "02", title: "Made personal", copy: "Start with a considered itinerary and make it yours, one conversation at a time." }, { number: "03", title: "Real human support", copy: "Travel with the confidence of having a real expert behind your journey." }, { number: "04", title: "From planning to memories", copy: "One team to help you before, during and after your time away." }].map((reason) => <div key={reason.number} className="border-t border-[#0d7a84]/25 pt-5" data-testid={`why-${reason.number}`}><span className="font-mono text-xs text-[#0d7a84]">{reason.number}</span><h3 className="mt-8 font-serif text-2xl text-[#1a1d20]">{reason.title}</h3><p className="mt-3 text-sm leading-relaxed text-[#5a6065]">{reason.copy}</p></div>)}</div></div></section>
    <DestinationRail title="Explore the world" eyebrow="Beyond the familiar" copy="A few places we keep returning to, for good reason." destinations={destinations} />
    <DestinationRail title="Closer to home" eyebrow="India, beautifully" copy="Journeys that remind you how much there is to see without crossing a border." destinations={domesticDestinations} muted />
    <DestinationRail title="Just pack your bags" eyebrow="Visa-free beginnings" copy="Less paperwork, more possibility. Start with the places that make leaving easy." destinations={visaFreeDestinations} />
    <section id="stories" className="bg-[#182d30] px-5 py-16 text-white sm:px-8 lg:px-12 lg:py-24" data-testid="traveller-stories-section"><div className="mx-auto max-w-[1440px]"><div className="grid gap-10 lg:grid-cols-[0.8fr_1.2fr] lg:items-end"><SectionHeading eyebrow="In their words" title="Travellers tell the story better." copy="The most useful travel advice is personal. These are a few notes from people who have gone with us." light /><div className="relative overflow-hidden border border-white/15 bg-white/10"><img src={review.image} alt={`Traveller story from ${review.name}`} className="aspect-[16/9] w-full object-cover opacity-75" /><div className="absolute inset-0 bg-gradient-to-t from-[#182d30] via-transparent to-transparent" /><div className="absolute left-5 top-5 flex items-center gap-2"><span className="grid h-10 w-10 place-items-center rounded-full bg-white text-[#0d7a84]"><Play className="ml-0.5 h-4 w-4 fill-current" /></span><Badge className="border-0 bg-[#0d7a84] text-white">{review.platform}</Badge></div><div className="absolute bottom-5 left-5 right-5"><p className="max-w-lg font-serif text-2xl leading-tight sm:text-3xl">“{review.quote}”</p><div className="mt-4 flex items-center justify-between text-xs text-white/65"><span>{review.name}</span><span className="flex items-center gap-1 text-[#9de9e6]">{review.rating} <Heart className="h-3.5 w-3.5 fill-current" /></span></div></div></div></div><div className="mt-7 flex items-center justify-between"><a href={review.url} target="_blank" rel="noreferrer" className="text-sm text-[#9de9e6] transition-colors hover:text-white" data-testid="review-original-link">Read the original story ↗</a><div className="flex gap-2"><button type="button" aria-label="Previous traveller story" onClick={() => setReviewIndex((index) => (index - 1 + travellerReviews.length) % travellerReviews.length)} className="grid h-10 w-10 place-items-center border border-white/25 transition-colors hover:bg-white/10" data-testid="review-previous-button"><ChevronLeft className="h-4 w-4" /></button><button type="button" aria-label="Next traveller story" onClick={() => setReviewIndex((index) => (index + 1) % travellerReviews.length)} className="grid h-10 w-10 place-items-center border border-white/25 transition-colors hover:bg-white/10" data-testid="review-next-button"><ChevronRight className="h-4 w-4" /></button></div></div></div></section>
    <section className="mx-auto max-w-[1440px] px-5 py-16 sm:px-8 lg:px-12 lg:py-24" data-testid="campaign-section"><div className="relative min-h-[420px] overflow-hidden rounded-xl"><img src={featuredCampaign.image} alt="Autumn in Japan" loading="lazy" className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-r from-[#101b1d]/80 via-[#101b1d]/25 to-transparent" /><div className="relative flex min-h-[420px] max-w-xl flex-col justify-end p-7 text-white sm:p-12"><p className="font-mono text-[10px] uppercase tracking-[0.22em] text-[#a8f1ef]">{featuredCampaign.eyebrow}</p><h2 className="mt-4 font-serif text-4xl leading-tight sm:text-5xl">{featuredCampaign.title}</h2><p className="mt-4 max-w-md text-sm leading-relaxed text-white/75">{featuredCampaign.copy}</p><Link to={featuredCampaign.href} className="mt-7 inline-flex w-fit items-center gap-2 border-b border-[#a8f1ef] pb-2 text-sm text-white transition-colors hover:text-[#a8f1ef]" data-testid="campaign-cta">{featuredCampaign.cta} <ArrowRight className="h-4 w-4" /></Link></div></div></section>
    <section className="bg-[#f2ede4] px-5 py-16 text-center sm:px-8 lg:px-12 lg:py-24" data-testid="home-final-cta"><p className="font-mono text-[10px] uppercase tracking-[0.22em] text-[#0d7a84]">The next chapter</p><h2 className="mx-auto mt-4 max-w-2xl font-serif text-4xl leading-tight text-[#1a1d20] sm:text-6xl">Where will you go next?</h2><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><Link to="/destinations" className={cn(buttonVariants({ variant: "default", size: "lg" }), "gap-2 bg-[#0d7a84] text-white hover:bg-[#0a5e66]")} data-testid="final-explore-destinations-button">Explore destinations <ArrowUpRight className="h-4 w-4" /></Link><button type="button" onClick={() => openWhatsApp()} className="inline-flex h-11 items-center justify-center gap-2 border border-[#0d7a84]/35 px-5 text-sm font-medium text-[#0d7a84] transition-colors hover:bg-white" data-testid="final-talk-button">Talk to Tentwood <MessageCircle className="h-4 w-4" /></button></div></section>
  </SiteLayout>;
}

function DestinationRail({ title, eyebrow, copy, destinations: items, muted = false }: { title: string; eyebrow: string; copy: string; destinations: typeof destinations; muted?: boolean }) { return <section className={cn("px-5 py-16 sm:px-8 lg:px-12 lg:py-24", muted ? "bg-[#f8f5ee]" : "bg-[#fdfbf7]")} data-testid={`destination-rail-${title.toLowerCase().replaceAll(" ", "-")}`}><div className="mx-auto max-w-[1440px]"><SectionHeading eyebrow={eyebrow} title={title} copy={copy} action={<Link to="/destinations" className="hidden items-center gap-2 text-sm text-[#0d7a84] md:flex" data-testid={`rail-view-all-${title.toLowerCase().replaceAll(" ", "-")}`}>View all <ArrowRight className="h-4 w-4" /></Link>} /><div className="mt-9 flex gap-5 overflow-x-auto pb-3 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{items.map((destination) => <div key={destination.slug} className="min-w-[280px] flex-1 lg:min-w-[0]"><DestinationCard destination={destination} compact /></div>)}</div></div></section>; }