import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { ArrowRight, ArrowUpRight, ChevronLeft, ChevronRight, Heart, MessageCircle, Play, Sparkles } from "lucide-react";
import { buttonVariants } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { domesticDestinations, internationalDestinations, visaFreeDestinations } from "@/data/destinations";
import { journeys } from "@/data/journeys";
import { featuredCampaign } from "@/data/campaigns";
import { travellerReviews } from "@/data/reviews";
import type { Destination } from "@/data/types";
import { openWhatsApp } from "@/lib/whatsapp";
import { cn } from "@/lib/utils";
import { DestinationCard, FilterBar, JourneyCard, SearchBar, SectionHeading, Seo, SiteLayout } from "@/components/site/Shared";

export default function Home() {
  const [filters, setFilters] = useState<Record<string, string>>({ Destination: "All Destinations", Budget: "All budgets", "Travel type": "All travellers", Duration: "Any duration" });
  const [reviewIndex, setReviewIndex] = useState(0);
  const visibleJourneys = useMemo(() => journeys.filter((journey) => {
    const days = Number(journey.duration.match(/(\d+)\s*Days/i)?.[1] ?? 0);
    const durationMatches = filters.Duration === "Any duration" || (filters.Duration === "3–5 Days" && days >= 3 && days <= 5) || (filters.Duration === "6–9 Days" && days >= 6 && days <= 9) || (filters.Duration === "10+ Days" && days >= 10);
    return (filters.Destination === "All Destinations" || journey.destination === filters.Destination) && (filters.Budget === "All budgets" || journey.budget === filters.Budget) && (filters["Travel type"] === "All travellers" || journey.travelType === filters["Travel type"]) && durationMatches;
  }), [filters]);
  useEffect(() => { const reduce = window.matchMedia("(prefers-reduced-motion: reduce)").matches; if (reduce) return; const timer = window.setInterval(() => setReviewIndex((index) => (index + 1) % travellerReviews.length), 3000); return () => window.clearInterval(timer); }, []);
  const review = travellerReviews[reviewIndex];
  return <SiteLayout><Seo title="Travel, thoughtfully designed" description="Tentwood Trips creates curated journeys, beautiful places and experiences designed around the way you travel." />
    <section className="relative min-h-[780px] overflow-hidden bg-[#0d7a84] px-5 pb-20 pt-36 text-white sm:px-8 lg:min-h-[880px] lg:px-12 lg:pb-24 lg:pt-48" data-testid="home-hero">
      <img src="https://images.unsplash.com/photo-1540202404-a2f29016b523?auto=format&fit=crop&w=2400&q=90" alt="Aerial view of a tropical island and turquoise sea" className="animate-cinematic-reveal absolute inset-0 h-full w-full scale-[1.03] object-cover object-center saturate-[0.92] contrast-[1.06]" />
      <div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(7,38,42,0.93)_0%,rgba(7,38,42,0.48)_48%,rgba(7,38,42,0.08)_78%),linear-gradient(0deg,rgba(7,38,42,0.34),transparent_55%)]" />
      <div className="relative mx-auto flex min-h-[620px] max-w-[1440px] flex-col justify-between lg:min-h-[650px]">
        <div className="max-w-4xl"><div className="flex items-center gap-3"><span className="h-px w-12 bg-[#9de9e6]" /><span className="font-mono text-[9px] uppercase tracking-[0.28em] text-[#b6eeec]">Curated journeys · Since 2018</span></div><h1 className="mt-7 max-w-4xl text-balance font-serif text-[3.7rem] font-normal leading-[0.91] tracking-[-0.045em] sm:text-[5.8rem] lg:text-[8.3rem]">Travel,<br /><em className="font-normal text-[#b8efec]">thoughtfully</em> designed.</h1><p className="mt-7 max-w-xl text-base leading-[1.8] text-white/78 sm:text-lg">Curated journeys, beautiful places and experiences designed around the way you travel.</p><div className="mt-9 flex flex-col gap-3 sm:flex-row"><Link to="/destinations" className={cn(buttonVariants({ variant: "secondary", size: "lg" }), "justify-center gap-2 rounded-none bg-white px-6 text-[#0d7a84] hover:bg-[#e5f7f5]")} data-testid="hero-explore-button">Explore destinations <ArrowUpRight className="h-4 w-4" /></Link><button type="button" onClick={() => openWhatsApp("Hi Tentwood Trips! I’d like to plan a thoughtful journey.")} className="inline-flex h-11 items-center justify-center gap-2 border border-white/45 px-6 text-sm font-medium text-white transition-colors hover:bg-white/10" data-testid="hero-plan-trip-button">Plan my trip <MessageCircle className="h-4 w-4" /></button></div></div>
        <div className="mt-20 w-full max-w-2xl border-l-2 border-[#a8f1ef] bg-[#fdfbf7]/96 p-5 text-[#1a1d20] shadow-[0_22px_60px_rgba(5,31,34,0.22)] backdrop-blur-sm sm:p-7" data-testid="hero-search-panel"><div className="mb-4 flex items-center justify-between"><span className="font-mono text-[9px] uppercase tracking-[0.22em] text-[#0d7a84]">Begin anywhere</span><span className="flex items-center gap-1.5 text-xs text-[#5a6065]"><Sparkles className="h-3.5 w-3.5 text-[#d98a6c]" /> Personalised by people</span></div><SearchBar /></div>
      </div>
    </section>
    <section className="mx-auto max-w-[1440px] px-5 py-20 sm:px-8 lg:px-12 lg:py-32" data-testid="popular-journeys-section"><SectionHeading eyebrow="A good place to begin" title="Journeys travellers are choosing" copy="Discover where Tentwood travellers are heading next. Every route starts with a conversation, not a checkout." /><div className="mt-12"><FilterBar activeFilters={filters} setActiveFilters={setFilters} /><div className="mt-9 flex gap-5 overflow-x-auto pb-4 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden" data-testid="journey-carousel">{visibleJourneys.map((journey) => <JourneyCard key={journey.id} journey={journey} />)}{visibleJourneys.length === 0 && <div className="w-full border-y border-[#1a1d20]/10 py-14 text-center" data-testid="journey-filter-empty-state"><p className="font-serif text-3xl">No journey matches all four filters.</p><p className="mt-2 text-sm text-[#5a6065]">Try widening one choice and we’ll show you more possibilities.</p></div>}</div></div></section>
    <section className="bg-[#17383c] px-5 py-20 text-white sm:px-8 lg:px-12 lg:py-32" data-testid="why-tentwood-section"><div className="mx-auto grid max-w-[1440px] gap-14 lg:grid-cols-[0.78fr_1.22fr] lg:items-stretch"><div className="relative min-h-[520px] overflow-hidden"><img src="https://images.unsplash.com/photo-1526772662000-3f88f10405ff?auto=format&fit=crop&w=1200&q=86" alt="A traveller looking across a wide landscape" loading="lazy" className="absolute inset-0 h-full w-full object-cover opacity-75" /><div className="absolute inset-0 bg-gradient-to-t from-[#102f33]/95 via-[#102f33]/10 to-transparent" /><div className="relative flex h-full min-h-[520px] flex-col justify-end p-7 sm:p-10"><p className="font-mono text-[9px] uppercase tracking-[0.24em] text-[#a8f1ef]">The Tentwood way</p><blockquote className="mt-4 max-w-md font-serif text-4xl leading-[1.08] sm:text-5xl">“The finest journey is the one that feels entirely your own.”</blockquote><p className="mt-6 text-sm text-white/60">Planned by people. Remembered by you.</p></div></div><div className="flex flex-col justify-center"><SectionHeading eyebrow="Why us" title="Why travel with Tentwood?" copy="We take care of the considered details, so you can be fully there." light /><div className="mt-12 grid gap-x-10 sm:grid-cols-2">{[{ number: "01", title: "Thoughtfully curated", copy: "Every journey is built around places and experiences worth remembering." }, { number: "02", title: "Made personal", copy: "Start with a considered itinerary and make it yours, one conversation at a time." }, { number: "03", title: "Real human support", copy: "Travel with the confidence of having a real expert behind your journey." }, { number: "04", title: "From planning to memories", copy: "One team to help you before, during and after your time away." }].map((reason) => <div key={reason.number} className="group border-t border-white/18 py-7" data-testid={`why-${reason.number}`}><div className="flex items-start gap-5"><span className="font-serif text-4xl italic text-[#a8f1ef]/65">{reason.number}</span><div><h3 className="font-serif text-2xl font-normal">{reason.title}</h3><p className="mt-3 text-sm leading-[1.7] text-white/58">{reason.copy}</p></div></div></div>)}</div></div></div></section>
    <DestinationRail title="Explore the world" eyebrow="Beyond the familiar" copy="A few places we keep returning to, for good reason." destinations={internationalDestinations} />
    <DestinationRail title="Closer to home" eyebrow="India, beautifully" copy="Journeys that remind you how much there is to see without crossing a border." destinations={domesticDestinations} muted />
    <DestinationRail title="Just pack your bags" eyebrow="Visa-free beginnings" copy="Less paperwork, more possibility. Start with the places that make leaving easy." destinations={visaFreeDestinations} />
    <section id="stories" className="bg-[#182d30] px-5 py-16 text-white sm:px-8 lg:px-12 lg:py-24" data-testid="traveller-stories-section"><div className="mx-auto max-w-[1440px]"><div className="grid gap-10 lg:grid-cols-[0.8fr_1.2fr] lg:items-end"><SectionHeading eyebrow="In their words" title="Travellers tell the story better." copy="The most useful travel advice is personal. These are a few notes from people who have gone with us." light /><div className="relative overflow-hidden border border-white/15 bg-white/10"><img src={review.image} alt={`Traveller story from ${review.name}`} className="aspect-[16/9] w-full object-cover opacity-75" /><div className="absolute inset-0 bg-gradient-to-t from-[#182d30] via-transparent to-transparent" /><div className="absolute left-5 top-5 flex items-center gap-2"><span className="grid h-10 w-10 place-items-center rounded-full bg-white text-[#0d7a84]"><Play className="ml-0.5 h-4 w-4 fill-current" /></span><Badge className="border-0 bg-[#0d7a84] text-white">{review.platform}</Badge></div><div className="absolute bottom-5 left-5 right-5"><p className="max-w-lg font-serif text-2xl leading-tight sm:text-3xl">“{review.quote}”</p><div className="mt-4 flex items-center justify-between text-xs text-white/65"><span>{review.name}</span><span className="flex items-center gap-1 text-[#9de9e6]">{review.rating} <Heart className="h-3.5 w-3.5 fill-current" /></span></div></div></div></div><div className="mt-7 flex items-center justify-between"><a href={review.url} target="_blank" rel="noreferrer" className="text-sm text-[#9de9e6] transition-colors hover:text-white" data-testid="review-original-link">Read the original story ↗</a><div className="flex gap-2"><button type="button" aria-label="Previous traveller story" onClick={() => setReviewIndex((index) => (index - 1 + travellerReviews.length) % travellerReviews.length)} className="grid h-10 w-10 place-items-center border border-white/25 transition-colors hover:bg-white/10" data-testid="review-previous-button"><ChevronLeft className="h-4 w-4" /></button><button type="button" aria-label="Next traveller story" onClick={() => setReviewIndex((index) => (index + 1) % travellerReviews.length)} className="grid h-10 w-10 place-items-center border border-white/25 transition-colors hover:bg-white/10" data-testid="review-next-button"><ChevronRight className="h-4 w-4" /></button></div></div></div></section>
    <section className="mx-auto max-w-[1440px] px-5 py-20 sm:px-8 lg:px-12 lg:py-32" data-testid="campaign-section"><div className="relative min-h-[500px] overflow-hidden"><img src={featuredCampaign.image} alt="Autumn in Japan" loading="lazy" className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-r from-[#101b1d]/84 via-[#101b1d]/20 to-transparent" /><div className="relative flex min-h-[500px] max-w-xl flex-col justify-end p-7 text-white sm:p-14"><p className="font-mono text-[9px] uppercase tracking-[0.24em] text-[#a8f1ef]">{featuredCampaign.eyebrow}</p><h2 className="mt-4 font-serif text-5xl font-normal leading-[1.02] sm:text-6xl">{featuredCampaign.title}</h2><p className="mt-5 max-w-md text-sm leading-[1.8] text-white/72">{featuredCampaign.copy}</p><Link to={featuredCampaign.href} className="mt-8 inline-flex w-fit items-center gap-2 border-b border-[#a8f1ef] pb-2 text-sm text-white transition-colors hover:text-[#a8f1ef]" data-testid="campaign-cta">{featuredCampaign.cta} <ArrowRight className="h-4 w-4" /></Link></div></div></section>
    <section className="bg-[#f2ede4] px-5 py-16 text-center sm:px-8 lg:px-12 lg:py-24" data-testid="home-final-cta"><p className="font-mono text-[10px] uppercase tracking-[0.22em] text-[#0d7a84]">The next chapter</p><h2 className="mx-auto mt-4 max-w-2xl font-serif text-4xl leading-tight text-[#1a1d20] sm:text-6xl">Where will you go next?</h2><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><Link to="/destinations" className={cn(buttonVariants({ variant: "default", size: "lg" }), "gap-2 bg-[#0d7a84] text-white hover:bg-[#0a5e66]")} data-testid="final-explore-destinations-button">Explore destinations <ArrowUpRight className="h-4 w-4" /></Link><button type="button" onClick={() => openWhatsApp()} className="inline-flex h-11 items-center justify-center gap-2 border border-[#0d7a84]/35 px-5 text-sm font-medium text-[#0d7a84] transition-colors hover:bg-white" data-testid="final-talk-button">Talk to Tentwood <MessageCircle className="h-4 w-4" /></button></div></section>
  </SiteLayout>;
}

function DestinationRail({ title, eyebrow, copy, destinations: items, muted = false }: { title: string; eyebrow: string; copy: string; destinations: Destination[]; muted?: boolean }) { const railId = title.toLowerCase().replaceAll(" ", "-"); return <section className={cn("px-5 py-20 sm:px-8 lg:px-12 lg:py-32", muted ? "bg-[#f5f0e8]" : "bg-[#fdfbf7]")} data-testid={`destination-rail-${railId}`}><div className="mx-auto max-w-[1440px]"><SectionHeading eyebrow={eyebrow} title={title} copy={copy} action={<Link to="/destinations" className="hidden items-center gap-2 border-b border-[#0d7a84]/30 pb-1 text-sm text-[#0d7a84] md:flex" data-testid={`rail-view-all-${railId}`}>View all <ArrowRight className="h-4 w-4" /></Link>} /><div className="mt-12 flex gap-5 overflow-x-auto pb-3 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden">{items.map((destination) => <div key={destination.slug} className="min-w-[300px] flex-1 lg:min-w-[320px]"><DestinationCard destination={destination} compact testIdSuffix={railId} /></div>)}</div></div></section>; }