import { Link, useLocation } from "react-router-dom";
import { ArrowUpRight } from "lucide-react";
import { buttonVariants } from "@/components/ui/button";
import { PageIntro, Seo, SiteLayout } from "@/components/site/Shared";
import { cn } from "@/lib/utils";

const pages: Record<string, { title: string; eyebrow: string; description: string; sections: { heading: string; copy: string }[] }> = {
  "/privacy": { title: "Privacy, plainly explained.", eyebrow: "Privacy policy", description: "How Tentwood Trips handles information shared during travel enquiries.", sections: [{ heading: "What you share", copy: "The showcase does not store enquiry form submissions. Information entered into an enquiry is prepared locally in your browser and only leaves the site when you choose to continue to WhatsApp or email." }, { heading: "Third-party services", copy: "WhatsApp, email and social platforms apply their own privacy terms once you open those services. Tentwood does not load social embeds or advertising trackers on this showcase." }, { heading: "Questions", copy: "For a privacy question or data request, contact hello@tentwoodtrips.com and our team will respond directly." }] },
  "/terms": { title: "Terms of using this showcase.", eyebrow: "Terms & conditions", description: "Terms for browsing Tentwood Trips journey ideas and requesting travel planning assistance.", sections: [{ heading: "Journey information", copy: "Routes, prices and availability shown here are indicative showcase content. A Tentwood travel expert will confirm current inclusions, supplier availability and final pricing before any booking." }, { heading: "No online booking", copy: "This site does not take payment or create a confirmed booking. WhatsApp and email actions begin a conversation only." }, { heading: "Content", copy: "Tentwood’s writing, presentation and journey concepts are provided for personal travel research and may not be republished commercially without permission." }] },
  "/cancellation": { title: "Cancellation, with clarity.", eyebrow: "Cancellation policy", description: "How cancellation terms are communicated for Tentwood Trips journeys.", sections: [{ heading: "Before confirmation", copy: "Submitting an enquiry or opening WhatsApp does not create a booking, so there is nothing to cancel at the showcase stage." }, { heading: "After confirmation", copy: "Cancellation timelines and supplier charges vary by journey. Your final proposal will clearly state the applicable terms before payment or confirmation." }, { heading: "Need help?", copy: "If plans change, contact Tentwood as early as possible. A travel expert will explain the options available for your confirmed arrangements." }] },
  "/faq": { title: "A few useful answers.", eyebrow: "Frequently asked questions", description: "Answers about planning a journey with Tentwood Trips.", sections: [{ heading: "Can I personalise an itinerary?", copy: "Yes. Every published route is a considered starting point. Dates, pace, stays and experiences can be shaped around the way you travel." }, { heading: "How do I request a trip?", copy: "Complete a destination enquiry or use any Tentwood WhatsApp button. The site prepares a message with your details for you to review before sending." }, { heading: "Are prices final?", copy: "Displayed prices are realistic starting estimates. Final pricing depends on travel dates, party size, room choice and current supplier availability." }, { heading: "Is my form saved?", copy: "No. This showcase does not persist form submissions. You remain in control and choose whether to continue through WhatsApp or email." }] },
};

export default function InfoPage() {
  const { pathname } = useLocation();
  const page = pages[pathname] ?? pages["/faq"]!;
  return <SiteLayout><Seo title={page.eyebrow} description={page.description} /><PageIntro eyebrow="Tentwood Trips" title={page.title} copy={page.description} /><section className="mx-auto max-w-4xl px-5 py-16 sm:px-8 lg:py-24"><div className="grid gap-9">{page.sections.map((section, index) => <article key={section.heading} className="border-t border-[#1a1d20]/12 pt-6" data-testid={`info-section-${index + 1}`}><span className="font-mono text-[9px] uppercase tracking-[0.2em] text-[#0d7a84]">0{index + 1}</span><h2 className="mt-4 font-serif text-[2rem] font-normal sm:text-4xl">{section.heading}</h2><p className="mt-3 max-w-2xl text-[15px] leading-[1.8] text-[#5a6065]">{section.copy}</p></article>)}</div><Link to="/contact" className={cn(buttonVariants({ variant: "default" }), "mt-12 min-h-12 w-full gap-2 bg-[#0d7a84] text-white sm:w-fit")} data-testid="info-contact-button">Talk to Tentwood <ArrowUpRight className="h-4 w-4" /></Link></section></SiteLayout>;
}